### ISSUE TITLE
[Feat] JPA 연동

### ISSUE THREAD

**Issue by JuneParkCode** [Kernel360/hackathon2-gyeonggiBus#14]
## 기능
- 설계된 DB 를 바탕으로 JPA Entity 를 작성하고 Repository 를 작성합니다.

## Todo
- [x] 정류소 Table 에 대한 Entity 작성
- [x] 버스 노선 Table 에 대한 Entity 작성
- [x] 위치정보에 대한 Entity 작성
  - 위치 정보를 활용할 경우 경유 정류소에 대한 부분도 필요함.
- [x] 노선별 경유 정류소에 대한 Entity 작성
- [x] 데이터 수집 요청에 대한 Entity 작성
- [x] 각 Entity 에 대응하는 Repository 작성

## 참고
[ERD Cloud - 변경본](https://www.erdcloud.com/d/FsXXtecptAbz4ErjT)
